spring:
  application:
    name: eureka-server2

server:
  port: 8762

eureka:
  instance:
    metadataMap.zone: zone2
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#     server:
#       waitTimeInMsWhenSyncEmpty: 0