spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    metadataMap.zone: zone1
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#     server:
#       waitTimeInMsWhenSyncEmpty: 0